1.Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [7]:
import numpy as np
print((np.ones((10,10)) - np.pad(np.ones((8,8)), 1, constant_values=0)).astype(int))

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


2.Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [11]:
import numpy as np
print((np.indices((8,8)).sum(axis=0) % 2))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3.Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [14]:
import numpy as np
print(np.diag([1,2,3,4], k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


4.Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее вдоль каждой строки было равно нулю.

In [15]:
import numpy as np
a = np.random.rand(5,5); print(a - a.mean(axis=1, keepdims=True))

[[ 0.10686592  0.26569503  0.34323932 -0.27647498 -0.43932528]
 [ 0.04234791 -0.26557168  0.03017206  0.54222299 -0.34917128]
 [-0.03868728  0.29890627 -0.01249934 -0.01633315 -0.23138651]
 [-0.08742777  0.19332779  0.06261759 -0.28952387  0.12100626]
 [-0.18519767 -0.28875842 -0.07226481  0.2081338   0.33808709]]


5.Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [16]:
import numpy as np
a = np.random.rand(10,3); print(a[np.arange(10), np.argmin(np.abs(a-0.5), axis=1)])

[0.31030429 0.3993174  0.44740598 0.62599743 0.53122034 0.59098937
 0.8405495  0.41138172 0.40737556 0.32551115]


6.Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [17]:
import numpy as np
a = np.random.rand(6,6); print(a.sum(axis=1) / a.max(axis=0))

[3.73317586 2.23141866 4.3970064  3.6946121  3.96489629 2.79043452]


7.На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [19]:
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]); print(np.max(x[1:][x[:-1] == 0]))

5


8.Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [21]:
import numpy as np
x, i = np.ones(10), np.array([0,1,2,3,5,5,5,8]); np.add.at(x, i, 1); print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


9.Задайте два массива a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]]) и b = np.array([3, 5, 10, 0]). Создайте массив, в котором каждый элемент первого массива заменен на ближайший к нему элемент второго массива.

In [24]:
import numpy as np
a, b = np.array([[1,4.9,2.4],[7.1,7.9,8],[2,4.6,1.2]]), np.array([3,5,10,0]); print(b[np.argmin(np.abs(a[...,None]-b), axis=-1)])

[[ 0  5  3]
 [ 5 10 10]
 [ 3  5  0]]


10.Найдите скользящие средние с окном размера 3 по массиву a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2]).

In [26]:
import numpy as np
a = np.array([1,4.9,2.4,7.1,7.9,8,2,-5,4.6,1.2]); print(np.convolve(a, np.ones(3)/3, mode='valid'))

[2.76666667 4.8        5.8        7.66666667 5.96666667 1.66666667
 0.53333333 0.26666667]
